# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: HParker
email: adamhess1991[at]gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, This is Adam. I am a software developer. Here is where I plan to write
  my thoughts about software development and coding.
baseurl: "" # the subpath of your site, e.g. /blog
url: "hparker.github.io" # the base hostname & protocol for your site
twitter_username: theHessParker
github_username:  HParker

# Build settings
markdown: kramdown
