baseURL = "https://hparker.xyz/"
languageCode = "en-us"
title = "HParker"
theme = "researcher"
enableEmoji = true
math = false # enable KaTeX (https://katex.org/) globally

[params]
  author = "Adam Hess"
  description = "A Website about software by Adam Hess"
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  # logo = "me.png"  # url or path to a logo to put in the header
  [params.footer]
    text = "By Adam Hess"
    url = "https://hparker.xyz"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Inconsolata"
    pageWidth = "750px"
    avatarSize = "90px"
    colorBlack = "#222222"
    colorRed = "#172ac4"
  [[params.socialIcons]]
    icon = "fab fa-twitter"
    title = "Twitter"
    url = "https://twitter.com/hparker"
  [[params.socialIcons]]
    icon = "fab fa-github"
    title = "Twitter"
    url = "https://github.com/hparker"
  [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "E-mail"
    url = "mailto:hparker[at]hey.com"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "http://words.hparker.io/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects"
    weight = 2
  [[menu.main]]
    name = "Art"
    url = "/art"
    weight = 3

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
